CREATE INDEX `advisoryRequests_clientId_idx` ON `advisoryRequests` (`clientId`);--> statement-breakpoint
CREATE INDEX `advisoryRequests_status_idx` ON `advisoryRequests` (`status`);--> statement-breakpoint
CREATE INDEX `appointmentWorkTypes_appointmentId_idx` ON `appointmentWorkTypes` (`appointmentId`);--> statement-breakpoint
CREATE INDEX `appointments_clientId_idx` ON `appointments` (`clientId`);--> statement-breakpoint
CREATE INDEX `appointments_scheduledDate_idx` ON `appointments` (`scheduledDate`);--> statement-breakpoint
CREATE INDEX `appointments_status_idx` ON `appointments` (`status`);--> statement-breakpoint
CREATE INDEX `appointments_client_status_idx` ON `appointments` (`clientId`,`status`);--> statement-breakpoint
CREATE INDEX `clientRevisionHistory_projectId_idx` ON `client_revision_history` (`projectId`);--> statement-breakpoint
CREATE INDEX `clients_userId_idx` ON `clients` (`userId`);--> statement-breakpoint
CREATE INDEX `clients_whatsappPhone_idx` ON `clients` (`whatsappPhone`);--> statement-breakpoint
CREATE INDEX `colombianHolidays_year_idx` ON `colombianHolidays` (`year`);--> statement-breakpoint
CREATE INDEX `colombianHolidays_date_idx` ON `colombianHolidays` (`date`);--> statement-breakpoint
CREATE INDEX `expenses_projectId_idx` ON `expenses` (`projectId`);--> statement-breakpoint
CREATE INDEX `expenses_expenseDate_idx` ON `expenses` (`expenseDate`);--> statement-breakpoint
CREATE INDEX `expenses_expenseType_idx` ON `expenses` (`expenseType`);--> statement-breakpoint
CREATE INDEX `hardwareCatalog_category_idx` ON `hardwareCatalog` (`category`);--> statement-breakpoint
CREATE INDEX `hardwareCatalog_active_idx` ON `hardwareCatalog` (`active`);--> statement-breakpoint
CREATE INDEX `kitchenQuotations_quotationId_idx` ON `kitchenQuotations` (`quotationId`);--> statement-breakpoint
CREATE INDEX `notifications_userId_idx` ON `notifications` (`userId`);--> statement-breakpoint
CREATE INDEX `notifications_read_idx` ON `notifications` (`read`);--> statement-breakpoint
CREATE INDEX `notifications_user_read_idx` ON `notifications` (`userId`,`read`);--> statement-breakpoint
CREATE INDEX `pricingConfig_category_idx` ON `pricingConfig` (`category`);--> statement-breakpoint
CREATE INDEX `pricingHistory_pricingConfigId_idx` ON `pricingHistory` (`pricingConfigId`);--> statement-breakpoint
CREATE INDEX `priorEstimates_clientId_idx` ON `priorEstimates` (`clientId`);--> statement-breakpoint
CREATE INDEX `projectDetails_projectId_idx` ON `projectDetails` (`projectId`);--> statement-breakpoint
CREATE INDEX `projectHardwareSelections_projectId_idx` ON `projectHardwareSelections` (`projectId`);--> statement-breakpoint
CREATE INDEX `projectHardwareSelections_hardwareId_idx` ON `projectHardwareSelections` (`hardwareId`);--> statement-breakpoint
CREATE INDEX `projectMaterials_projectId_idx` ON `projectMaterials` (`projectId`);--> statement-breakpoint
CREATE INDEX `projectPayments_projectId_idx` ON `projectPayments` (`projectId`);--> statement-breakpoint
CREATE INDEX `projectPhotos_projectId_idx` ON `projectPhotos` (`projectId`);--> statement-breakpoint
CREATE INDEX `projectPhotos_category_idx` ON `projectPhotos` (`category`);--> statement-breakpoint
CREATE INDEX `projectPhotos_project_category_idx` ON `projectPhotos` (`projectId`,`category`);--> statement-breakpoint
CREATE INDEX `projectStatusHistory_projectId_idx` ON `projectStatusHistory` (`projectId`);--> statement-breakpoint
CREATE INDEX `projects_clientId_idx` ON `projects` (`clientId`);--> statement-breakpoint
CREATE INDEX `projects_status_idx` ON `projects` (`status`);--> statement-breakpoint
CREATE INDEX `projects_createdAt_idx` ON `projects` (`createdAt`);--> statement-breakpoint
CREATE INDEX `projects_quotationId_idx` ON `projects` (`quotationId`);--> statement-breakpoint
CREATE INDEX `projects_designerId_idx` ON `projects` (`designerId`);--> statement-breakpoint
CREATE INDEX `projects_createdBy_idx` ON `projects` (`createdBy`);--> statement-breakpoint
CREATE INDEX `pushSubscriptions_userId_idx` ON `pushSubscriptions` (`userId`);--> statement-breakpoint
CREATE INDEX `quotationItems_quotationId_idx` ON `quotationItems` (`quotationId`);--> statement-breakpoint
CREATE INDEX `quotations_clientId_idx` ON `quotations` (`clientId`);--> statement-breakpoint
CREATE INDEX `quotations_status_idx` ON `quotations` (`status`);--> statement-breakpoint
CREATE INDEX `quotations_createdBy_idx` ON `quotations` (`createdBy`);--> statement-breakpoint
CREATE INDEX `quotations_createdAt_idx` ON `quotations` (`createdAt`);--> statement-breakpoint
CREATE INDEX `reminders_projectId_idx` ON `reminders` (`projectId`);--> statement-breakpoint
CREATE INDEX `reminders_assignedTo_idx` ON `reminders` (`assignedTo`);--> statement-breakpoint
CREATE INDEX `reminders_dueDate_idx` ON `reminders` (`dueDate`);--> statement-breakpoint
CREATE INDEX `reminders_status_idx` ON `reminders` (`status`);--> statement-breakpoint
CREATE INDEX `tasks_assignedTo_idx` ON `tasks` (`assignedTo`);--> statement-breakpoint
CREATE INDEX `tasks_status_idx` ON `tasks` (`status`);--> statement-breakpoint
CREATE INDEX `tasks_dueDate_idx` ON `tasks` (`dueDate`);--> statement-breakpoint
CREATE INDEX `tasks_projectId_idx` ON `tasks` (`projectId`);--> statement-breakpoint
CREATE INDEX `tasks_assigned_status_idx` ON `tasks` (`assignedTo`,`status`);--> statement-breakpoint
CREATE INDEX `users_role_idx` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `users_email_idx` ON `users` (`email`);