import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, text, foreignKey, int, mysqlEnum, timestamp, varchar, decimal, json, bigint, tinyint } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const drizzleMigrations = mysqlTable("__drizzle_migrations__", {
	id: bigint({ mode: "number" }).autoincrement().notNull(),
	hash: text().notNull(),
	createdAt: bigint("created_at", { mode: "number" }),
},
(table) => [
	index("id").on(table.id),
]);

export const advisoryRequests = mysqlTable("advisoryRequests", {
	id: int().autoincrement().notNull(),
	clientId: int().notNull().references(() => clients.id),
	workType: mysqlEnum(['cocina','closet','puertas','centro_tv']).notNull(),
	status: mysqlEnum(['pendiente','contactado','completado']).default('pendiente').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	preferredCallTime: text(),
},
(table) => [
	index("advisoryRequests_clientId_idx").on(table.clientId),
	index("advisoryRequests_status_idx").on(table.status),
]);

export const appointmentWorkTypes = mysqlTable("appointmentWorkTypes", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull().references(() => appointments.id, { onDelete: "cascade" } ),
	workType: mysqlEnum(['cocina','closet','puertas','centro_tv']).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("appointmentWorkTypes_appointmentId_idx").on(table.appointmentId),
]);

export const appointments = mysqlTable("appointments", {
	id: int().autoincrement().notNull(),
	clientId: int().notNull().references(() => clients.id),
	scheduledDate: timestamp({ mode: 'string' }),
		status: mysqlEnum(['pendiente','confirmada','completada','cancelada']).default('pendiente').notNull(),
		notes: text(),
		createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
		updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
		deletedAt: timestamp({ mode: 'string' }),
		dataOrigin: mysqlEnum(['manual', 'system']).default('manual').notNull(),
	},
(table) => [
	index("appointments_clientId_idx").on(table.clientId),
	index("appointments_scheduledDate_idx").on(table.scheduledDate),
	index("appointments_status_idx").on(table.status),
	index("appointments_client_status_idx").on(table.clientId, table.status),
]);

export const clientRevisionHistory = mysqlTable("client_revision_history", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull().references(() => projects.id, { onDelete: "cascade" } ),
	type: mysqlEnum(['modelado_3d','renders']).notNull(),
	revisionNumber: int().notNull(),
	clientName: varchar({ length: 255 }).notNull(),
	changes: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("clientRevisionHistory_projectId_idx").on(table.projectId),
]);

	export const clients = mysqlTable("clients", {
		id: int().autoincrement().notNull(),
		userId: int().references(() => users.id),
		name: varchar({ length: 255 }).notNull(),
		email: varchar({ length: 320 }),
		whatsappPhone: varchar({ length: 20 }).notNull(),
		address: text(),
		createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
		updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
		internalManagement: tinyint().default(0).notNull(),
		deletedAt: timestamp({ mode: 'string' }),
		dataOrigin: mysqlEnum(['manual', 'system']).default('manual').notNull(),
	},
(table) => [
	index("clients_userId_idx").on(table.userId),
	index("clients_whatsappPhone_idx").on(table.whatsappPhone),
]);

export const colombianHolidays = mysqlTable("colombianHolidays", {
	id: int().autoincrement().notNull(),
	date: timestamp({ mode: 'string' }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	year: int().notNull(),
},
(table) => [
	index("colombianHolidays_year_idx").on(table.year),
	index("colombianHolidays_date_idx").on(table.date),
]);

export const expenses = mysqlTable("expenses", {
	id: int().autoincrement().notNull(),
	expenseType: mysqlEnum(['materiales_proyecto','gasto_operativo']).notNull(),
	projectId: int().references(() => projects.id, { onDelete: "set null" } ),
	projectClientName: varchar({ length: 255 }),
	operativeCategory: mysqlEnum(['arriendo','energia','agua','internet','mantenimiento','herramientas','jardineria','reparaciones','transporte','papeleria','aseo','otro']),
	description: text().notNull(),
	amount: decimal({ precision: 12, scale: 2 }).notNull(),
	expenseDate: timestamp({ mode: 'string' }).notNull(),
	supportUrl: text(),
	supportFileName: varchar({ length: 255 }),
	createdBy: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	generalCategory: mysqlEnum(['materiales','mano_de_obra','alquiler','servicios','transporte','mantenimiento','otros']).notNull(),
	subcategory: varchar({ length: 255 }),
},
(table) => [
	index("expenses_projectId_idx").on(table.projectId),
	index("expenses_expenseDate_idx").on(table.expenseDate),
	index("expenses_expenseType_idx").on(table.expenseType),
]);

export const hardwareCatalog = mysqlTable("hardwareCatalog", {
	id: int().autoincrement().notNull(),
	category: mysqlEnum(['cocinas','closets','puertas']).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	options: text(),
	photoUrl: text(),
	sortOrder: int().default(0).notNull(),
	active: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	price: decimal({ precision: 12, scale: 2 }).default('0').notNull(),
},
(table) => [
	index("hardwareCatalog_category_idx").on(table.category),
	index("hardwareCatalog_active_idx").on(table.active),
]);

export const kitchenQuotations = mysqlTable("kitchenQuotations", {
	id: int().autoincrement().notNull(),
	quotationId: int().notNull(),
	shape: mysqlEnum(['L','U','lineal']).notNull(),
	totalMeters: decimal({ precision: 10, scale: 2 }).notNull(),
	resultingMeters: decimal({ precision: 10, scale: 2 }).notNull(),
	lowerCabinetsMeters: decimal({ precision: 10, scale: 2 }).notNull(),
	lowerCabinetsPrice: decimal({ precision: 12, scale: 2 }).notNull(),
	upperCabinetsMeters: decimal({ precision: 10, scale: 2 }).notNull(),
	upperCabinetsPrice: decimal({ precision: 12, scale: 2 }).notNull(),
	hasNichoNevecon: tinyint().default(0).notNull(),
	nichoNeveconPrice: decimal({ precision: 12, scale: 2 }),
	hasNichoNeveraStandard: tinyint().default(0).notNull(),
	nichoNeveraStandardPrice: decimal({ precision: 12, scale: 2 }),
	hasAlacenaEntrepanos: tinyint().default(0).notNull(),
	alacenaEntrepanosPrice: decimal({ precision: 12, scale: 2 }),
	hasAlacenaHerraje: tinyint().default(0).notNull(),
	alacenaHerrajePrice: decimal({ precision: 12, scale: 2 }),
	hasHerrajeItem: tinyint().default(0).notNull(),
	herrajePrice: decimal({ precision: 12, scale: 2 }),
	hasTorreHornos: tinyint().default(0).notNull(),
	torreHornosPrice: decimal({ precision: 12, scale: 2 }),
	countertopType: mysqlEnum(['quarzone','sinterizado']).notNull(),
	countertopMeters: decimal({ precision: 10, scale: 2 }).notNull(),
	countertopSurcharge30: tinyint().default(0).notNull(),
	countertopDouble: tinyint().default(0).notNull(),
	countertopPrice: decimal({ precision: 12, scale: 2 }).notNull(),
	hasIsland: tinyint().default(0).notNull(),
	islandCabinetsMeters: decimal({ precision: 10, scale: 2 }),
	islandCabinetsPrice: decimal({ precision: 12, scale: 2 }),
	islandCountertopMeters: decimal({ precision: 10, scale: 2 }),
	islandCountertopType: mysqlEnum(['quarzone','sinterizado']),
	islandCountertopPrice: decimal({ precision: 12, scale: 2 }),
	islandHasLaterals: tinyint().default(0).notNull(),
	islandLateralPrice: decimal({ precision: 12, scale: 2 }),
	islandRegruesoPrice: decimal({ precision: 12, scale: 2 }),
	islandTotalPrice: decimal({ precision: 12, scale: 2 }),
	hasBar: tinyint().default(0).notNull(),
	barCabinetsMeters: decimal({ precision: 10, scale: 2 }),
	barCabinetsPrice: decimal({ precision: 12, scale: 2 }),
	barCountertopMeters: decimal({ precision: 10, scale: 2 }),
	barCountertopType: mysqlEnum(['quarzone','sinterizado']),
	barCountertopPrice: decimal({ precision: 12, scale: 2 }),
	barHasLateral: tinyint().default(0).notNull(),
	barLateralPrice: decimal({ precision: 12, scale: 2 }),
	barTotalPrice: decimal({ precision: 12, scale: 2 }),
	hasLed: tinyint().default(0).notNull(),
	ledMeters: decimal({ precision: 10, scale: 2 }),
	ledPrice: decimal({ precision: 12, scale: 2 }),
	transportCost: decimal({ precision: 12, scale: 2 }).default('600000').notNull(),
	subtotal: decimal({ precision: 12, scale: 2 }).notNull(),
	total: decimal({ precision: 12, scale: 2 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	hasPaintedDoors: tinyint().default(0).notNull(),
	paintedDoorsUpperQty: int().default(0),
	paintedDoorsUpperPrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsLowerQty: int().default(0),
	paintedDoorsLowerPrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsPantryQty: int().default(0),
	paintedDoorsPantryPrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsDrawerQty: int().default(0),
	paintedDoorsDrawerPrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsSpiceQty: int().default(0),
	paintedDoorsSpicePrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsGolaQty: int().default(0),
	paintedDoorsGolaPrice: decimal({ precision: 12, scale: 2 }),
	paintedDoorsTotalPrice: decimal({ precision: 12, scale: 2 }),
},
(table) => [
	index("kitchenQuotations_quotationId_idx").on(table.quotationId),
]);

export const notifications = mysqlTable("notifications", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id),
	title: varchar({ length: 255 }).notNull(),
	body: text().notNull(),
	type: mysqlEnum(['proyecto','tarea','cita','cotizacion','sistema']).default('sistema').notNull(),
	referenceId: int(),
	referenceType: varchar({ length: 50 }),
	read: tinyint().default(0).notNull(),
	sentPush: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("notifications_userId_idx").on(table.userId),
	index("notifications_read_idx").on(table.read),
	index("notifications_user_read_idx").on(table.userId, table.read),
]);

export const pricingConfig = mysqlTable("pricingConfig", {
	id: int().autoincrement().notNull(),
	category: mysqlEnum(['cocina_base','mesones','muebles_especiales','extras','puertas_tapas','herrajes','closets','puertas_producto','centros_tv','otros','acabados_especiales']).notNull(),
	code: varchar({ length: 100 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	value: decimal({ precision: 12, scale: 2 }).notNull(),
	unit: varchar({ length: 50 }),
	sortOrder: int().default(0).notNull(),
	active: tinyint().default(1).notNull(),
	updatedBy: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("code").on(table.code),
	index("pricingConfig_category_idx").on(table.category),
]);

export const pricingHistory = mysqlTable("pricingHistory", {
	id: int().autoincrement().notNull(),
	pricingConfigId: int().notNull(),
	previousValue: decimal({ precision: 12, scale: 2 }).notNull(),
	newValue: decimal({ precision: 12, scale: 2 }).notNull(),
	changedBy: int().notNull(),
	reason: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("pricingHistory_pricingConfigId_idx").on(table.pricingConfigId),
]);

export const priorEstimates = mysqlTable("priorEstimates", {
	id: int().autoincrement().notNull(),
	clientId: int().notNull().references(() => clients.id),
	workType: mysqlEnum(['cocina','closet','puertas','centro_tv']).notNull(),
	additionalDetails: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	kitchenShape: mysqlEnum(['L','U','lineal']),
	materialType: mysqlEnum(['quarzone','sinterizado']),
	linearLength: decimal({ precision: 10, scale: 2 }),
	height: decimal({ precision: 10, scale: 2 }),
},
(table) => [
	index("priorEstimates_clientId_idx").on(table.clientId),
]);

export const projectDetails = mysqlTable("projectDetails", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull().references(() => projects.id),
	type: mysqlEnum(['medida_especial','nota_importante','foto_referencia']).notNull(),
	title: varchar({ length: 255 }).notNull(),
	content: text().notNull(),
	photoUrl: text(),
	createdBy: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("projectDetails_projectId_idx").on(table.projectId),
]);

export const projectHardwareSelections = mysqlTable("projectHardwareSelections", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull(),
	hardwareId: int().notNull(),
	selectedOption: text(),
	notes: text(),
	createdBy: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	quantity: int().default(1).notNull(),
	priceAtQuotation: decimal({ precision: 10, scale: 2 }),
},
(table) => [
	index("projectHardwareSelections_projectId_idx").on(table.projectId),
	index("projectHardwareSelections_hardwareId_idx").on(table.hardwareId),
]);

export const projectMaterials = mysqlTable("projectMaterials", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull(),
	woodType: mysqlEnum(['rh','estandar']),
	woodColor: varchar({ length: 255 }),
	woodPhotoUrl: text(),
	countertopType: mysqlEnum(['granito','cuarzo','sinterizado']),
	countertopName: varchar({ length: 255 }),
	countertopPhotoUrl: text(),
	sinkMeasure: varchar({ length: 100 }),
	sinkPhotoUrl: text(),
	notes: text(),
	createdBy: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("projectMaterials_projectId_idx").on(table.projectId),
]);

export const projectPayments = mysqlTable("projectPayments", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull().references(() => projects.id, { onDelete: "cascade" } ),
	type: mysqlEnum(['adelanto','saldo_final','abono','otro']).notNull(),
	amount: decimal({ precision: 12, scale: 2 }).notNull(),
	paymentDate: timestamp({ mode: 'string' }).notNull(),
	receiptUrl: text(),
	notes: text(),
	registeredBy: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("projectPayments_projectId_idx").on(table.projectId),
]);

export const projectPhotos = mysqlTable("projectPhotos", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull().references(() => projects.id),
	stage: mysqlEnum(['inicial','diseno','corte','enchape','ensamble','final']).notNull(),
	photoUrl: text().notNull(),
	description: text(),
	uploadedBy: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	category: mysqlEnum(['cotizacion','medidas','disenos','avance','instalacion','entrega']).default('medidas').notNull(),
	subcategory: mysqlEnum(['fotos_iniciales','dibujo','renders','despieces','detalles','modelado','modelado_3d','corte','enchape','armado','proceso_instalacion','fotos_finales','documento_cotizacion']),
},
(table) => [
	index("projectPhotos_projectId_idx").on(table.projectId),
	index("projectPhotos_category_idx").on(table.category),
	index("projectPhotos_project_category_idx").on(table.projectId, table.category),
]);

export const projectStatusHistory = mysqlTable("projectStatusHistory", {
	id: int().autoincrement().notNull(),
	projectId: int().notNull().references(() => projects.id),
	fromStatus: varchar({ length: 50 }),
	toStatus: varchar({ length: 50 }).notNull(),
	changedBy: int().notNull().references(() => users.id),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("projectStatusHistory_projectId_idx").on(table.projectId),
]);

export const projects = mysqlTable("projects", {
	id: int().autoincrement().notNull(),
	quotationId: int(),
	clientId: int().notNull().references(() => clients.id),
	name: varchar({ length: 255 }).notNull(),
	workType: mysqlEnum(['cocina','closet','puertas','centro_tv']).notNull(),
	status: mysqlEnum(['contacto','cotizacion_enviada','cotizacion_aprobada','adelanto_recibido','en_diseno','pendiente_modelado','pendiente_render','aprobacion_final','despiece','corte','enchape','ensamble','listo_instalacion','entregado']).default('contacto').notNull(),
	initialMeasurements: text(),
	design3DFiles: text(),
	despieceFiles: text(),
	clientApprovedAt: timestamp({ mode: 'string' }),
	clientApprovalNotes: text(),
	createdBy: int().notNull().references(() => users.id),
	designerId: int().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	quotationApprovedAt: timestamp({ mode: 'string' }),
	advanceReceivedAt: timestamp({ mode: 'string' }),
	totalAmount: decimal({ precision: 12, scale: 2 }),
	advanceAmount: decimal({ precision: 12, scale: 2 }),
	designDeadline: timestamp({ mode: 'string' }),
	designDeliveredAt: timestamp({ mode: 'string' }),
	selectedColors: text(),
	selectedMaterials: text(),
	estimatedInstallDate: timestamp({ mode: 'string' }),
	scheduledInstallDate: timestamp({ mode: 'string' }),
	installDurationDays: int().default(1),
	deliveredAt: timestamp({ mode: 'string' }),

	advanceReceiptUrl: text("advance_receipt_url"),
	quotationPdfUrl: text(),
	tentativeInstallDate: timestamp({ mode: 'string' }),
	isInstallDateOfficial: tinyint().default(0),
	modeladoApprovedAt: timestamp({ mode: 'string' }),
	modeladoApprovedBy: varchar({ length: 255 }),
	rendersApprovedAt: timestamp({ mode: 'string' }),
	rendersApprovedBy: varchar({ length: 255 }),
	renderRevisionNumber: int().default(0),
	modeladoRevisionNumber: int().default(0),
		changesRequestedAt: timestamp({ mode: 'string' }),
		deletedAt: timestamp({ mode: 'string' }),
		currentApprovedQuotationId: int(),
		dataOrigin: mysqlEnum(['manual', 'system']).default('manual').notNull(),
	},
(table) => [
	index("projects_quotationId_quotations_id_fk").on(table.quotationId),
	index("projects_clientId_idx").on(table.clientId),
	index("projects_status_idx").on(table.status),
	index("projects_createdAt_idx").on(table.createdAt),
	index("projects_quotationId_idx").on(table.quotationId),
	index("projects_designerId_idx").on(table.designerId),
	index("projects_createdBy_idx").on(table.createdBy),
]);

export const pushSubscriptions = mysqlTable("pushSubscriptions", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id),
	endpoint: text().notNull(),
	p256Dh: varchar({ length: 255 }).notNull(),
	auth: varchar({ length: 255 }).notNull(),
	userAgent: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("pushSubscriptions_userId_idx").on(table.userId),
]);

export const quotationItems = mysqlTable("quotationItems", {
	id: int().autoincrement().notNull(),
	quotationId: int().notNull().references(() => quotations.id, { onDelete: "cascade" } ),
	itemNumber: int().notNull(),
	itemType: varchar({ length: 50 }).default('otro').notNull(),
	description: text().notNull(),
	quantity: varchar({ length: 50 }).notNull(),
	unitPrice: varchar({ length: 50 }),
	totalPrice: decimal({ precision: 12, scale: 2 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	includesFixedCosts: tinyint().default(0).notNull(),
	kitchenConfig: json(),
	hardwareSelections: json(),
	closetConfig: json(),
	fixedCostsAmount: decimal({ precision: 12, scale: 2 }).default('600000'),
	doorConfig: json(),
	tvCenterConfig: json(),
	countertopConfig: json(),
},
(table) => [
	index("quotationItems_quotationId_idx").on(table.quotationId),
]);

export const quotations = mysqlTable("quotations", {
	id: int().autoincrement().notNull(),
	quotationNumber: varchar({ length: 50 }).notNull(),
	clientId: int().notNull().references(() => clients.id, { onDelete: "cascade" } ),
	vendorName: varchar({ length: 255 }).notNull(),
	productType: mysqlEnum(['cocina','closet','puerta','centro_tv','herrajes','mesones','acabados_especiales','otro']).default('otro').notNull(),
	status: mysqlEnum(['draft','sent','approved','rejected']).default('draft').notNull(),
	validUntil: timestamp({ mode: 'string' }),
	subtotal: decimal({ precision: 12, scale: 2 }).notNull(),
	transportCost: decimal({ precision: 12, scale: 2 }).default('600000').notNull(),
	total: decimal({ precision: 12, scale: 2 }).notNull(),
	pdfUrl: text(),
	sentAt: timestamp({ mode: 'string' }),
	createdBy: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	approvedAt: timestamp({ mode: 'string' }),
	rejectionReason: text(),
	customDescriptions: json(),
	generalNotes: text(),
	discountPercent: decimal({ precision: 5, scale: 2 }).default('0'),
	discountAmount: decimal({ precision: 15, scale: 2 }).default('0'),
	isLocked: tinyint().default(0).notNull(),
	lockedAt: timestamp({ mode: 'string' }),
	lockedBy: int(),
	parentQuotationId: int(),
	isAdditional: tinyint().default(0).notNull(),
	baseQuotationId: int(),
	versionNumber: int().default(1).notNull(),
	clientResponseStatus: mysqlEnum(['aprobado','rechazado','revision']),
	clientResponseNotes: text(),
		clientResponseAt: timestamp({ mode: 'string' }),
		whatsappApiSentAt: timestamp({ mode: 'string' }),
		deletedAt: timestamp({ mode: 'string' }),
		dataOrigin: mysqlEnum(['manual', 'system']).default('manual').notNull(),
		},
	(table) => [
		index("quotationNumber").on(table.quotationNumber),
	index("quotations_clientId_idx").on(table.clientId),
	index("quotations_status_idx").on(table.status),
	index("quotations_createdBy_idx").on(table.createdBy),
		index("quotations_createdAt_idx").on(table.createdAt),
		index("quotations_clientResponseStatus_idx").on(table.clientResponseStatus),
]);

export const reminders = mysqlTable("reminders", {
	id: int().autoincrement().notNull(),
	projectId: int().references(() => projects.id),
	type: mysqlEnum(['cotizacion_sin_respuesta','diseno_pendiente','aprobacion_pendiente','produccion_retrasada','instalacion_proxima']).notNull(),
	assignedTo: int().notNull().references(() => users.id),
	dueDate: timestamp({ mode: 'string' }).notNull(),
	status: mysqlEnum(['pendiente','enviado','completado','cancelado']).default('pendiente').notNull(),
	message: text(),
	sentAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("reminders_projectId_idx").on(table.projectId),
	index("reminders_assignedTo_idx").on(table.assignedTo),
	index("reminders_dueDate_idx").on(table.dueDate),
	index("reminders_status_idx").on(table.status),
]);

export const taskReminders = mysqlTable("taskReminders", {
	id: int().autoincrement().notNull(),
	taskId: int().notNull().references(() => tasks.id, { onDelete: "cascade" } ),
	sentBy: int().notNull().references(() => users.id),
	sentTo: int().notNull().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const tasks = mysqlTable("tasks", {
	id: int().autoincrement().notNull(),
	projectId: int().references(() => projects.id),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	priority: mysqlEnum(['alta','media','baja']).default('media').notNull(),
	status: mysqlEnum(['pendiente','en_progreso','completada']).default('pendiente').notNull(),
	dueDate: timestamp({ mode: 'string' }),
	assignedTo: int().notNull().references(() => users.id),
	assignedBy: int().notNull().references(() => users.id),
	completedAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastReminderSentAt: timestamp({ mode: 'string' }),
	lastReminderSentBy: int(),
	reminderCount: int().default(0).notNull(),
	deletedAt: timestamp({ mode: 'string' }),
},
(table) => [
	index("tasks_assignedTo_idx").on(table.assignedTo),
	index("tasks_status_idx").on(table.status),
	index("tasks_dueDate_idx").on(table.dueDate),
	index("tasks_projectId_idx").on(table.projectId),
	index("tasks_assigned_status_idx").on(table.assignedTo, table.status),
]);

	export const payments = mysqlTable("payments", {
		id: int().autoincrement().notNull(),
		projectId: int().notNull().references(() => projects.id, { onDelete: "cascade" }),
		amount: decimal({ precision: 12, scale: 2 }).notNull(),
		type: mysqlEnum(['advance','final','partial','other']).notNull(),
		receivedAt: timestamp({ mode: 'string' }).notNull(),
		method: varchar({ length: 100 }),
		notes: text(),
		registeredBy: int().references(() => users.id),
		createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	},
	(table) => [
		index("payments_projectId_idx").on(table.projectId),
		index("payments_receivedAt_idx").on(table.receivedAt),
	]);

		export const users = mysqlTable("users", {
		id: int().autoincrement().notNull(),
		openId: varchar({ length: 64 }).notNull(),
		name: text(),
		email: varchar({ length: 320 }),
		loginMethod: varchar({ length: 64 }),
		role: mysqlEnum(['user','admin','super_admin','comercial','disenador','jefe_taller','operario']).default('user').notNull(),
		phone: varchar({ length: 20 }),
		createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
		updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
		lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
		passwordHash: varchar({ length: 255 }),
		passwordResetToken: varchar({ length: 100 }),
		passwordResetExpires: timestamp({ mode: 'string' }),
			birthDate: timestamp({ mode: 'string' }),
		dataOrigin: mysqlEnum(['manual', 'system']).default('manual').notNull(),
		deletedAt: timestamp({ mode: 'string' }),
	},
(table) => [
	index("users_openId_unique").on(table.openId),
	index("users_role_idx").on(table.role),
	index("users_email_idx").on(table.email),
]);
